### ISSUE TITLE
Doesn't work if Playa is not installed

### ISSUE THREAD

**Issue by aasun** [EllisLab/PlayaMatrixImporter#1]
I've used this twice, so far.  Saves a lot of time. But, if I only have Matrix installed, the import errors out because it can't find any Playa info.  I can work around that by installing playa, then re-running.  But, that's an unnecessary hassle.

This latest build from a few days ago, also seems to have broken the Matrix import.  All the tables and rows are created and the data is there... Except for "col_id_1".  So, I have to export and import the data from the matrix data table.  Didn't have this problem with the first release.

Also, not seeing any change logs in the updates.  So, not sure what is changing with the code updates.

**Comment by kevincupp** [comment]
Sorry about that, should be an easy change to make it not require Playa, I'll make that change soon.

As for your other issue, to clarify, are you saying it imports all columns and their data except if there is a column ID of 1? And it omits that column only?

Also, there has only ever been [one public build](https://github.com/EllisLab/PlayaMatrixImporter/releases) of the importer. Did you happen to get a beta copy or something? There isn't a changelog since there has only been one release, we'll add one as there are more releases.

**Comment by aasun** [comment]
Hi There,

You’re right about the versions.  I just did the “day” math wrong in my head.  I thought 4 days was shorter.  I’ve only been using the single release. Sorry about that!

For the col_id_1 I reference.   In this particular instance, I only have 1 column in my old matrix (now grid) field.  Just images.  A screenshot of the data structure is included. After the import was done, the col_id_1 data was missing.  Though, the other columns (row_id, entry_id, row_order) were all there and contained the correct data.


Aasun
--
Aasun Eble, MBA
President and CEO
	Ottenhoff
Consulting, LLC
e-mail :   	aasun@ottenhoff.net <mailto:aasun@ottenhoff.net>
web :   	www.ottenhoff.net <http://www.ottenhoff.net/>
main :   	310-691-8154 x101
direct :   	909-570-2061
fax :   	310-946-0403

**Comment by aasun** [comment]
Here's an error that happened with another site.  This one has quite a few Matrix and Playa fields.  It also has multi-site manager (2 sites).  EE and all add-ons are up-to-date (EE2.10.3).  The migration failed with these errors seen.  No grid tables were created, and no partial migration was done of anything.

![screen shot 2016-03-12 at 13 43 23](https://cloud.githubusercontent.com/assets/5115281/13725505/7a612022-e858-11e5-9b05-acb93a5a9237.png)

**Comment by kevincupp** [comment]
Thanks, aasun. I've made a fix for not having Playa installed, and also allowed Matrix to not be installed. And I'm guessing the cause of the PHP errors you posted was that you had a Playa field that had no relationships, so I've put in a fix for that.

As for the missing column, I'm unable to reproduce that one. If you're willing, could you send me a dump of these tables BEFORE the import? (And if you still have them) You can email them if you like: kevin.cupp@ellislab.com

* `exp_grid_columns`
* `exp_matrix_cols`
* `exp_matrix_data`

Hope to be able to piece together something from that. Otherwise, I'll merge in my other fixes into the master branch and create a new release.
