### ISSUE TITLE
"Message: Undefined index:" for Assets conversion

### ISSUE THREAD

**Issue by howells** [EllisLab/PlayaMatrixImporter#10]
I seem to be getting a few errors with the Assets field convertor, but I'm not sure where to start debugging.

https://cl.ly/jBg8

Do you know what the issue could be?

**Comment by kevincupp** [comment]
I would guess you might have some orphaned Assets data, as in asset items that belong to a Matrix field that no longer exists. The error is happening when trying to map Matrix field ID 48 to its new Grid field, but it seems we didn't create a Grid field for that field ID, likely because it doesn't exist. So I would double-check that, and see if you have any other files in `exp_assets_selections` that map to non-existent fields.

In the first error, it also looks like it's trying to map a blank field ID, maybe you have a row in `exp_assets_selections` where the content type is `matrix` but the field ID is empty?

I guess I would look into these data anomalies and see if those rows that seem to have been orphaned need to belong somewhere else, or if you can just delete them.

**Comment by howells** [comment]
Oh okay, gosh I have no idea how I would check for orphans, there are many thousands of entries! Any ideas?

**Comment by kevincupp** [comment]
I would think a query like this would reveal any disassociated rows:

``` sql
SELECT * FROM exp_assets_selections WHERE content_type = 'matrix' AND field_id NOT IN (SELECT field_id FROM exp_channel_fields WHERE field_type = 'matrix')
```

**Comment by howells** [comment]
Thanks, I just tried that, but no rows are returned. Not sure what to do!

**Comment by howells** [comment]
Ah could it be something to do with matrixes used in Low Variables? These don't have field_ids (NULL) but do have var_id valies

**Comment by kevincupp** [comment]
Yes that could at least explain the first error message you got, we can build in some protection for that, and while we're in there, maybe we'll also set it to ignore orphaned columns and maybe that will fix your other error. To be clear, this is a Matrix field with an Assets column that's inside Low Variables?

**Comment by howells** [comment]
Sorry for the delay - yes, that is correct in this instance
