### ISSUE TITLE
getting Error Number: 1118

### ISSUE THREAD

**Issue by omejelle** [EllisLab/PlayaMatrixImporter#11]
EE 2.11.6 / php7 when running the script i'm getting these errors

A PHP Error was encountered

Severity: Warning

Message: Declaration of Fieldpack_dropdown_ft::replace_tag($data) should be compatible with Fieldpack_Multi_Fieldtype::replace_tag($data, $params = Array, $tagdata = false)

Filename: fieldpack/ft.fieldpack_dropdown.php

Line Number: 173

A PHP Error was encountered

Severity: Warning

Message: Declaration of Fieldpack_radio_buttons_ft::replace_tag($data) should be compatible with Fieldpack_Multi_Fieldtype::replace_tag($data, $params = Array, $tagdata = false)

Filename: fieldpack/ft.fieldpack_radio_buttons.php

Line Number: 154

A PHP Error was encountered

Severity: Warning

Message: Declaration of Matrix_ft::post_save() should be compatible with EE_Fieldtype::post_save($data)

Filename: matrix/ft.matrix.php

Line Number: 3796

A PHP Error was encountered

Severity: Warning

Message: Declaration of Matrix_ft::save_settings() should be compatible with EE_Fieldtype::save_settings($data)

Filename: matrix/ft.matrix.php

Line Number: 0

A PHP Error was encountered

Severity: Warning

Message: Declaration of Matrix_ft::post_save_settings() should be compatible with EE_Fieldtype::post_save_settings($data)

Filename: matrix/ft.matrix.php

Line Number: 0

A PHP Error was encountered

Severity: 8192

Message: Methods with the same name as their class will not be constructors in a future version of PHP; Zoo_visitor_ft has a deprecated constructor

Filename: zoo_visitor/ft.zoo_visitor.php

Line Number: 4

A Database Error Occurred
Error Number: 1118

Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

ALTER TABLE `exp_channel_data` ADD `field_ft_116` tinytext NULL

Filename: C:\Users\Jelle\Documents\websites\ihe\website\backstage\codeigniter\system\database\DB_driver.php

Line Number: 380

**Comment by kevincupp** [comment]
It looks like you have some fieldtypes with that are overriding methods with incomplete method signatures, this is due to PHP 7. So for example, you'd want to open ft.fieldpack_dropdown.php and look for:

``` php
function replace_tag($data)
```

And replace it with

``` php
function replace_tag($data, $params = array(), $tagdata = false)
```

Go down the error list for each fieldtype file listed and look to see which method signature it wants you to replace and replace them.

As for the Zoo Visitors fieldtype, there is likely a function in there declared like `function Zoo_visitor_ft()` but it needs to be `function __construct()`.

As for the row size error, it sounds like you have too many columns in your `channel_data` table. This is just a limitation of MySQL and unfortunately the only way around it is to find a way to consolidate or live without some of the custom fields on this site.

Going to close this since the issues are external to this add-on.
