### ISSUE TITLE
Matrix to Grid, Assets fields

### ISSUE THREAD

**Issue by 620studio** [EllisLab/PlayaMatrixImporter#13]
I'm upgrading to EE3 on an older EE2 site that started with using Matrix in a lot of fields. Used the importer which seemed to work well except for any Matrix fields that includes Assets as the cell type didn't migrate any of the content over. My client has over 1500 products with multiple images which I was hoping I wasn't going to have to manually update.

What's interesting is the new Grid settings migrated over just fine, it just didn't save the content itself. 90% of the way there, however that last 10% is going take quite to some time if we have to do it manually.

Thanks for any info or suggestions you can give.

EE 2.11.6, Assets 3.0.3, Matrix 3.0.8

**Comment by kevincupp** [comment]
Hmm it's difficult to say, many have successfully migrated Assets data. Typically, this kind of thing happens when the database is in some state that the importer didn't expect, and the best way for us to figure that out is to actually see the database. Would you be willing to send me a copy of this database to kevin.cupp@ellislab.com? You can exclude things like member data or anything else sensitive if you like.

**Comment by kevincupp** [comment]
Closing for over a year of inactivity.
