### ISSUE TITLE
Version to run on EE3?

### ISSUE THREAD

**Issue by Wartybliggens** [EllisLab/PlayaMatrixImporter#6]
I have been updating an EE 2.4.0 site to the latest 3.4.x, and would like to run this as an add-on on the updated version of the site, now that I've gotten the updater to run to the end, and discovered how the templates have Playa and Matrix tags (not to mention ce_cache... ugh).

**Comment by kevincupp** [comment]
The add-on is more designed to be run on EE2 so that you can make sure the importer has done its job before committing to the results. I currently don't see us investing the time into making and maintaining an EE3 version along side an EE2 version just for people who forgot they had these add-ons installed. I'd see if you could roll back and upgrade to the latest 2.x, run the importer, then upgrade to 3. Sorry!
