### ISSUE TITLE
Duplicate Column Name Error

### ISSUE THREAD

**Issue by joelcollyer** [EllisLab/PlayaMatrixImporter#9]
We're upgrading a site to EEv3 (from v2.11) and running the importer is producing this error after churning for several minutes:

```
A Database Error Occurred
Error Number: 1060

Duplicate column name 'col_id_1'

ALTER TABLE `exp_channel_grid_field_1752` ADD `col_id_1` text NULL

Filename: libraries/api/Api_channel_fields.php

Line Number: 675
```

**Comment by kevincupp** [comment]
Sorry for the trouble, Joel. We won't really be able to look into this without steps to reproduce. Are you able to send us a copy of your database? If so, send it to us in an email at team@ellislab.com. Maybe just omit your members table.

**Comment by joelcollyer** [comment]
Thanks for the speedy response! I've redacted some private data (members and form submissions) and sent a copy of our db (from just before the importer is run) to the address you specified above.

**Comment by kevincupp** [comment]
Thanks, Joel! It looks like this database has a lot of orphaned Grid fields in it, which is what is causing this error. It's trying to add a column to a table that already exists because the table shouldn't be there. Maybe the importer was previously run before but those `exp_channel_grid_field_x` tables weren't deleted before trying again?

If I first delete those tables and then run the importer, I get an error saying there are too many columns in your `channel_data` table, which unfortunately doesn't have much of a solution except for trying to remove unneeded fields, it's just a limit of MySQL. I'd imagine once you clear enough room for the new Grid fields, the importer should run just fine, provided your memory limit and max execution time are high enough (this is a huge database!).

**Comment by joelcollyer** [comment]
Rolled back our database, removed a couple of dead field groups, and was able to successfully run the import. Thanks for the help Kevin!

**Comment by kevincupp** [comment]
Awesome, glad to hear, sure thing!
